src/main/java/com/ekiryuhin/SpringTest2/domain/Message.java
package com.ekiryuhin.SpringTest2.domain;

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;

@Entity
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotBlank(message = "Please fill the message")
    @Length(max = 2048, message = "Message too long (>2kb)")
    private String text;
    @Length(max = 255, message = "Tag too long (>255b)")
    private String tag;
    private String filename;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User author;

    public Message() {
    }

    public Message(String text, String tag, User user) {
        this.text = text;
        this.tag = tag;
        this.author = user;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public Long getAuthorId() { return author.getId(); }

    public String getAuthorName() {
        return author != null ? author.getUsername() : "<none>";
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }
}

src/main/java/com/ekiryuhin/SpringTest2/controllers/GreetingController.java
package com.ekiryuhin.SpringTest2.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

import java.util.Map;

@Controller
public class GreetingController {

    @GetMapping("/greeting")
    public String greeting(Map<String, Object> model) {
        return "greeting";
    }
}

src/main/java/com/ekiryuhin/SpringTest2/controllers/ProfileController.java
package com.ekiryuhin.SpringTest2.controllers;

import com.ekiryuhin.SpringTest2.domain.Role;
import com.ekiryuhin.SpringTest2.domain.User;
import com.ekiryuhin.SpringTest2.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class ProfileController {
    private final UserService userService;

    @Autowired
    public ProfileController(UserService userService) {
        this.userService = userService;
    }

    @GetMapping("/profile/{user}")
    public String userProfile(@PathVariable User user, @AuthenticationPrincipal User logUser, Model model) {

        model.addAttribute("logUser", logUser);
        model.addAttribute("user", user);
        model.addAttribute("roles", Role.values());
        return "profile";
    }

    @PostMapping("/profile/{user}")
    public String saveProfile(@PathVariable User user,
                              @RequestParam String email,
                              @RequestParam String password
    ) {

        userService.updateProfile(user, email, password);

        return "profile";
    }

}

src/main/java/com/ekiryuhin/SpringTest2/controllers/RegistrationController.java
package com.ekiryuhin.SpringTest2.controllers;

import com.ekiryuhin.SpringTest2.domain.User;
import com.ekiryuhin.SpringTest2.domain.dto.CaptchaResponseDto;
import com.ekiryuhin.SpringTest2.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.client.RestTemplate;

import javax.validation.Valid;
import java.util.Collections;
import java.util.Map;

@Controller
public class RegistrationController {

    private final static String RECAPTCHA_URL ="https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s";

    private final
    UserService userService;

    private final
    RestTemplate restTemplate;

    @Value("${recaptcha.secret}")
    String recaptchaSecret;

    @Autowired
    public RegistrationController(UserService userService, RestTemplate restTemplate) {
        this.userService = userService;
        this.restTemplate = restTemplate;
    }

    @GetMapping("/registration")
    public String registration() {
        return "registration";
    }

    @PostMapping("/registration")
    public String addUser(@RequestParam("confPassword") String confPassword,
                          @RequestParam("g-recaptcha-response") String captchaResponse,
                          @Valid User user,
                          BindingResult bindingResult,
                          Model model) {

        String url = String.format(RECAPTCHA_URL, recaptchaSecret, captchaResponse);
        CaptchaResponseDto response = restTemplate.postForObject(url, Collections.emptyList(), CaptchaResponseDto.class);

        if (!response.isSuccess()) {
            model.addAttribute("captchaError", "Fill captcha");
        }

        boolean isConfirmEmpty = StringUtils.isEmpty(confPassword);
        if (isConfirmEmpty)
            model.addAttribute("passwordConfError", "Password confirmation cannot be empty");

        boolean isPasswordConfirmFailed = user.getPassword() != null && !user.getPassword().equals(confPassword);
        if (isPasswordConfirmFailed) {
            model.addAttribute("passwordConfError", "Passwords are different");
        }

        if (isConfirmEmpty || bindingResult.hasErrors() || !response.isSuccess() || isPasswordConfirmFailed) {
            Map<String, String> errors = ControllerUtils.getErrors(bindingResult);
            model.mergeAttributes(errors);
            return "registration";
        }

        if (!userService.addUser(user)) {
            model.addAttribute("usernameError", "User exists!");
            return "registration";
        }
        return "redirect:/login";
    }

    @GetMapping("/activate/{code}")
    public String activate(Model model, @PathVariable String code) {
        boolean isActivated = userService.activateUser(code);
        if (isActivated) {
            model.addAttribute("message", "User activated");
            model.addAttribute("messageType", "success");
        } else {
            model.addAttribute("message", "Activation code is not found");
            model.addAttribute("messageType", "danger");
        }
        return "login";
    }

}

src/main/resources/templates/greeting.ftl
<#import "parts/common.ftl" as cpage>
<@cpage.page>
<h1>Hello!</h1>
<a href="/main">Main page</a>
</@cpage.page>

src/main/resources/templates/index.ftl
<#import "parts/common.ftl" as cpage>
<#import "parts/login.ftl" as login>

<@cpage.page>

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Just my SpringBoot project</h1>
        <p class="lead">This is a page with some messages and pictures</p>
    </div>
</div>

<a class="btn btn-primary" data-toggle="collapse" href="#collapseForm" role="button" aria-expanded="false"
   aria-controls="collapseExample">
    Add new
    <Message></Message>
</a>
<div class="collapse <#if message??>show</#if> shadow p-3 mb-5 bg-white rounded" id="collapseForm">
    <div class="form-group mt-3">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group ml-4 col-sm-6">
                <input type="text" class="form-control ${(textError??)?string('is-invalid', '')}"
                       value="<#if message??>${message.text}</#if>" name="text" placeholder="Введите сообщение:">
                 <#if textError??>
                <div class="invalid-feedback">
                    ${textError}
                </div>
                 </#if>
            </div>
            <div class="form-group ml-4 col-sm-3">
                <input type="text" class="form-control ${(textError??)?string('is-invalid', '')}"
                       value="<#if message??>${message.tag}</#if>" name="tag" placeholder="Тэг">
                <#if tagError??>
                <div class="invalid-feedback">
                    ${tagError}
                </div>
                </#if>
            </div>
            <div class="form-group ml-4 col-sm-3">
                <div class="custom-file">
                    <input hidden="hidden" type="file" name="file" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
            </div>
            <input type="hidden" name="_csrf" value="${_csrf.token}"/>
            <div class="form-group ml-5">
                <button class="btn btn-outline-success" type="submit">Добавить</button>
            </div>
        </form>
    </div>
</div>

<form class="mt-5" method="get" action="/main">
    <div class="row">
        <div class="col-8">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Find by tag" name="filter"
                       value="${filter?if_exists}">
            </div>
        </div>
        <div class="col-2">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>

</form>


<div class="card-columns">
    <#list messages as message>

        <div class="card my-3 shadow p-3 mb-5 bg-white rounded" style="width: 18rem;">
        <#if message.filename??>
        <img class="card-img-top" src="/img/${message.filename}">
        </#if>
            <div class="card-body">
                <h5 class="card-title">#${message.id}</h5>
                <p class="card-text">${message.text}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Tag: ${message.tag}</li>
            </ul>
            <div class="card-body">
                <a href="/profile/${message.authorId}" class="card-link">Author: ${message.authorName}</a>
            </div>

        </div>
    <#else>
No message
    </#list>
</div>
</@cpage.page>

src/main/resources/templates/login.ftl
<#import "parts/common.ftl" as cpage>
<#import "parts/login.ftl" as logForm>
<@cpage.page>
<h1>Login page</h1>
    <#if Session?? && Session.SPRING_SECURITY_LAST_EXCEPTION??>
    <div class="alert alert-danger" role="alert">
        ${Session.SPRING_SECURITY_LAST_EXCEPTION.message}
    </div>
    </#if>
    <#if message??>
    <div class="alert alert-${messageType}" role="alert">
        ${message}
    </div>
    </#if>
    <@logForm.logForm "/login" false/>
</@cpage.page>

src/main/resources/templates/news.ftl
<#import "parts/common.ftl" as cpage>
<@cpage.page>

</@cpage.page>

src/main/resources/templates/profile.ftl
<#import "parts/common.ftl" as cpage>
<#import "parts/userdata.ftl" as userdata>
<@cpage.page>
    <@userdata.info/>
    <#include "parts/security.ftl">
    <#assign
    selfProfile = (currentUser.id == user.id)
    />
    <#if selfProfile>
    <h2>Edit</h2>
    <form method="post" class="col-sm-6">
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-10">
                <input type="email" name="email"  class="form-control" value=${user.email!''}>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Password:</label>
            <div class="col-sm-10">
                <input type="password" name="password"  class="form-control">
            </div>
        </div>
        <div class="text-right">
            <input type="hidden" name="_csrf" value = "${_csrf.token}"/>
            <input class="btn btn-primary" type="submit" value="Save"/>
        </div>
    </form>
    </#if>
</@cpage.page>

src/main/resources/templates/registration.ftl
<#import "parts/common.ftl" as cpage>
<#import "parts/login.ftl" as logForm>
<@cpage.page>
    <h1>Registration</h1>
    <@logForm.logForm "/registration" true />
</@cpage.page>

src/main/resources/templates/useredit.ftl
<#import "parts/common.ftl" as cpage>

<@cpage.page>
    <div class="shadow p-3 mb-5 bg-white rounded">
    <h1>User editor</h1>
    <form action="/user" method="post">
        <input type="hidden" name="userId" value="${user.id}">
        <div class="form-group mt-4 col-sm-4">
            <input type="text" class="form-control" name="username" value="${user.username}">
        </div>
        <#list roles as role>
            <div class="form-group form-check ml-4">
                <label><input type="checkbox" class="form-check-input" name="${role}" ${user.roles?seq_contains(role)?string("checked", "")}>${role}</label>
            </div>
        </#list>
        <input type="hidden" name="_csrf" value = "${_csrf.token}"/>
        <button type="submit" class="btn btn-outline-warning btn-lg ml-4" >Save</button>
    </form>
    </div>
</@cpage.page>

src/main/resources/templates/userlist.ftl
<#import "parts/common.ftl" as cpage>

<@cpage.page>
<h1>User list</h1>
<table class="table shadow p-3 mb-5 bg-white rounded">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Role</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <#list users as user>
    <tr>
        <td><a href="/profile/${user.id}">${user.username}</a></td>
        <td><#list user.roles as role>${role}<#sep>, </#list></td>
        <td><a href="/user/${user.id}">edit</a></td>
    </tr>
    </#list>
    </tbody>
</table>
</@cpage.page>